apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    {{- include "witness.labels" . | nindent 4 }}
data:
  witness.yml: |
    db_path: "db/"
    http_port: {{ .Values.port }}
    public_url: "{{ if .Values.publicUrl }}{{ .Values.publicUrl }}{{ else }}http://{{ .Values.ingress.subdomain }}.{{ .Release.Namespace }}.{{ .Values.ingress.baseDomain }}{{ end }}"
    seed: "${SEED}"
    escrow_config:
      default_timeout: 60
