apiVersion: v1
kind: Service
metadata:
  name: mesagkesto
  labels:
    {{- include "dkms-demo.labels" . | nindent 4 }}
    app: mesagkesto
spec:
  type: NodePort
  selector:
    app: mesagkesto
  ports:
    - port: {{ .Values.mesagkesto.port }}
      targetPort: {{ .Values.mesagkesto.port }}
      nodePort: {{ .Values.mesagkesto.nodePort }}
      protocol: TCP
