apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
  labels:
    {{- include "dkms-demo.labels" . | nindent 4 }}
    app: watcher
data:
  watcher.yml: |
    db_path: "db/"
    tel_storage_path: "db/tel_storage"
    public_url: "http://{{ .Values.externalHost }}:{{ .Values.watcher.nodePort }}"
    seed: "{{ .Values.watcher.seed }}"
    http_port: {{ .Values.watcher.port }}
    initial_oobis:
    {{- range .Values.witnesses }}
      - eid: "{{ .eid }}"
        scheme: "http"
        url: "http://{{ .name }}:{{ .port }}/"
    {{- end }}
    escrow_config:
      default_timeout: 60
