apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watcher-pvc
  labels:
    {{- include "dkms-demo.labels" . | nindent 4 }}
    app: watcher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- include "dkms-demo.storageClass" . | nindent 2 }}
