apiVersion: v1
kind: Service
metadata:
  name: watcher
  labels:
    {{- include "dkms-demo.labels" . | nindent 4 }}
    app: watcher
spec:
  type: NodePort
  selector:
    app: watcher
  ports:
    - port: {{ .Values.watcher.port }}
      targetPort: {{ .Values.watcher.port }}
      nodePort: {{ .Values.watcher.nodePort }}
      protocol: TCP
