{{- range .Values.witnesses }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- include "dkms-demo.labels" $ | nindent 4 }}
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.witness.repository }}:{{ $.Values.image.witness.tag }}"
          imagePullPolicy: {{ $.Values.image.witness.pullPolicy }}
          ports:
            - containerPort: {{ .port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/witness.yml
              subPath: witness.yml
            - name: db
              mountPath: /app/db
      volumes:
        - name: config
          configMap:
            name: {{ .name }}-config
        - name: db
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
{{- end }}
