{{- range .Values.witnesses }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
  labels:
    {{- include "dkms-demo.labels" $ | nindent 4 }}
    app: {{ .name }}
data:
  witness.yml: |
    db_path: "db/"
    http_port: {{ .port }}
    public_url: "http://{{ $.Values.externalHost }}:{{ .nodePort }}/"
    seed: "{{ .seed }}"
    escrow_config:
      default_timeout: 60
{{- end }}
