{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mesagkesto-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mesagkesto.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.subdomain }}.{{ .Release.Namespace }}.{{ .Values.ingress.baseDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mesagkesto
                port:
                  number: {{ .Values.port }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.subdomain }}.{{ .Release.Namespace }}.{{ .Values.ingress.baseDomain }}
      secretName: mesagkesto-tls-secret
  {{- end }}
{{- end }}
